### ISSUE TITLE
404 "Path not found"

### ISSUE THREAD

**Issue by Juwan-Hollingsworth** [dellius-alexander/Cordova-React-App#1]
Hey Dellius, 

I was able to pull down the project, install the dependencies and serve this on my local environment however I am getting a 404 error trying to move forward. Any suggestions?

**Comment by dellius-alexander** [comment]
Install Cordova  with: 'npm  install Cordova',  and/or use nodemon or node to start and build. Build scripts are in the scripts directory.

**Comment by Juwan-Hollingsworth** [comment]
Issue fixed, thanks for clarity nodemon fixed the issue!
